# This job is to test different maven profiles in master branch again Pull Request raised
# This workflow targets Java with Maven execution

name: TestNG SDK Test workflow for Maven

on:
  pull_request:
    branches: [ "sdk" ]
    types: [ opened, reopened ]
  issue_comment:
    types: [ created ]

jobs:
  if: ${{ github.event.comment.body == 'RUN_TESTS' || contains(fromJson('["opened", "reopened"]'), github.event.action)}}
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '8', '17' ]
        os: [ 'macos-latest', 'windows-latest' ]
    name: TestNG Repo ${{ matrix.Java }} - ${{ matrix.os }} Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          browser: chrome
          version: latest
          java-version: ${{ matrix.java }}
      - name: Run mvn test
        run: |
          mvn compile
          mvn test
      - name: Run mvn profile skip-browserstack-test
        run: |
          mvn compile
          mvn test -P skip-browserstack-test
      - name: Run mvn profile sample-local-test
        run: |
          mvn compile
          mvn test -P sample-local-test
      - name: Run mvn profile sample-test
        run: |
          mvn compile
          mvn test -P sample-test
